#!/bin/bash

# Render Deployment Script for Polyspack E-commerce Platform
# This script provides instructions for manual deployment to Render

echo "🚀 Polyspack E-commerce Platform - Render Deployment Guide"
echo "========================================================"
echo ""

echo "📋 Prerequisites:"
echo "1. Render account: https://render.com"
echo "2. GitHub repository connected to Render"
echo "3. MongoDB Atlas database set up"
echo "4. Required API keys and credentials"
echo ""

echo "🔧 Backend Deployment (Web Service):"
echo "-------------------------------------"
echo "1. Go to https://render.com and log in"
echo "2. Click 'New' → 'Web Service'"
echo "3. Connect your GitHub repo: ecommerce-polyspack"
echo "4. Select branch: blackboxai/production-ready"
echo "5. Configure settings:"
echo "   - Name: polyspack-backend"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: node server.js"
echo ""

echo "🌍 Environment Variables for Backend:"
echo "--------------------------------------"
echo "NODE_ENV=production"
echo "PORT=10000"
echo "MONGO_URI=mongodb+srv://username:password@cluster.mongodb.net/polyspack-ecommerce"
echo "JWT_SECRET=your_secure_jwt_secret_here"
echo "EMAIL_USER=noreply@polyspack.com"
echo "EMAIL_PASS=your_email_app_password"
echo "CLOUDINARY_CLOUD_NAME=your_cloudinary_name"
echo "CLOUDINARY_API_KEY=your_cloudinary_key"
echo "CLOUDINARY_API_SECRET=your_cloudinary_secret"
echo "MPESA_CONSUMER_KEY=your_mpesa_consumer_key"
echo "MPESA_CONSUMER_SECRET=your_mpesa_consumer_secret"
echo "MPESA_SHORTCODE=522533"
echo "MPESA_PASSKEY=your_mpesa_passkey"
echo ""

echo "🎨 Frontend Deployment (Static Site):"
echo "-------------------------------------"
echo "1. Click 'New' → 'Static Site'"
echo "2. Connect the same GitHub repo: ecommerce-polyspack"
echo "3. Select branch: blackboxai/production-ready"
echo "4. Configure settings:"
echo "   - Name: polyspack-frontend"
echo "   - Build Command: cd frontend && npm run build"
echo "   - Publish Directory: frontend/out"
echo ""

echo "🌍 Environment Variable for Frontend:"
echo "--------------------------------------"
echo "NEXT_PUBLIC_API_URL=https://polyspack-backend.onrender.com/api"
echo "(Replace with your actual backend URL after deployment)"
echo ""

echo "📝 Next Steps:"
echo "--------------"
echo "1. Deploy the backend first"
echo "2. Note the backend URL (e.g., https://polyspack-backend.onrender.com)"
echo "3. Update the frontend's NEXT_PUBLIC_API_URL with the backend URL"
echo "4. Deploy the frontend"
echo "5. Test the application"
echo ""

echo "🔗 Live URLs (after deployment):"
echo "---------------------------------"
echo "Frontend: https://polyspack-frontend.onrender.com"
echo "Backend API: https://polyspack-backend.onrender.com/api"
echo ""

echo "⚠️  Important Notes:"
echo "-------------------"
echo "- MongoDB Atlas: Set up a free cluster and get connection string"
echo "- Email Service: Use Gmail app password for EMAIL_PASS"
echo "- Payment Integration: Get MPESA credentials from Safaricom"
echo "- Cloudinary: Set up account for image uploads"
echo "- JWT Secret: Generate a secure random string"
echo ""

echo "🧪 Testing Checklist:"
echo "---------------------"
echo "- [ ] Backend server starts successfully"
echo "- [ ] Frontend builds without errors"
echo "- [ ] API endpoints respond correctly"
echo "- [ ] Authentication works"
echo "- [ ] Payment integration functions"
echo "- [ ] Email notifications send"
echo ""

echo "🎉 Deployment Complete!"
echo "Your Polyspack E-commerce platform will be live at:"
echo "https://polyspack-frontend.onrender.com"
